### ISSUE TITLE
php 8.4 deprecations

### ISSUE THREAD

**Issue by lekoala** [silverstripe/vendor-plugin#86] opened 2024-11-21 13:37 UTC
### Module version(s) affected

2

### Description

Running with php 8.4 gives deprecation errors that are easily fixable

Deprecation Notice: SilverStripe\VendorPlugin\Methods\CopyMethod::__construct(): Implicitly marking parameter $filesystem as nullable is deprecated, the explicit nullable type must be used instead
Deprecation Notice: SilverStripe\VendorPlugin\Methods\SymlinkMethod::__construct(): Implicitly marking parameter $filesystem as nullable is deprecated, the explicit nullable type must be used instead

### How to reproduce

install php 8.4
run composer
see the deprecation error

### Possible Solution

this is going to probably be the case on many modules so maybe a coordinated action using rector automation would be the best path

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment] 2024-11-25 20:15
Closing as a duplicate of https://github.com/silverstripe/.github/issues/331
We haven't added PHP 8.4 support yet - and when we do it will be for CMS 6 only as per the major release policy.

**Closed by GuySartorelli** 2024-11-25 20:15 UTC
