### ISSUE TITLE
This plugin uses symfony console, but does not require it so a newer version can be included breaking build processes.

### ISSUE THREAD

**Issue by nlighteneddesign** [silverstripe/vendor-plugin#84] opened 2024-09-30 20:41 UTC
### Module version(s) affected

2.0.3

### Description

As far as I can tell this project expects symfony/console 6 (recipe plugin too)
but there is no dependency, so if you update you get console 7 and a bunch of errors.

This is the root cause of #82

### How to reproduce

Check the composer.json for this project.

### Possible Solution

Add a dependency for the symfony console version this supports.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment] 2024-10-23 20:46
> This is the root cause of #82

Closing as a duplicate of #82

**Closed by GuySartorelli** 2024-10-23 20:46 UTC
